#!/bin/sh



REPOS="$1"
REV="$2"
USER="$3"
PROPNAME="$4"
ACTION="$5"
#TXN="$2"

SVNLOOK=/usr/bin/svnlook
LOGMSG=$($SVNLOOK log -t "$REV" "$REPOS" | grep "[a-zA-Z0-9]" | wc -c)


#if [ "$LOGMSG" -lt 10 ]; then
#   echo -e "\n 修改注释必须不能为空，提交中止."1>&2
#   exit 1;
#fi


if [ "$ACTION" = "M" -a "$PROPNAME" = "svn:log" ]; then 

exit 0;

fi

echo "Changing revision properties other than svn:log is prohibited" >&2
exit 1
